spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #          issuer-uri: "http://${app.auth-server-host}:${app.auth-server-port}/realms/key-gateway"
          jwk-set-uri: "http://${app.auth-server-host}:${app.auth-server-port}/realms/key-gateway/protocol/openid-connect/certs"
      client:
        provider:
          keycloak:
            issuer-uri: "http://${app.auth-server-host}:${app.auth-server-port}/realms/key-gateway"
        registration:
          swagger:
            provider: keycloak
            client-id: swagger
            client-secret: rdm1TckD9ZQuOwABwU9DRwdT8ObiV6v5
            authorization-grant-type: authorization_code
            scope: openid,offline_access,profile

server.port: 8088
app:
  eureka-server: localhost
  eureka-username: admin
  eureka-password: admin
  auth-server-host: localhost
  auth-server-port: 9090
  product-url: http://product
  recommendation-url: http://recommendation
  review-url: http://review

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.cloud.gateway:
  default-filters:
    - TokenRelay=
  routes:
    - id: product-composite
      uri: lb://product-composite
      predicates:
        - Path=/product-composite/**

    - id: product-composite-swagger-ui
      uri: lb://product-composite
      predicates:
        - Path=/openapi/**

    - id: eureka-api
      uri: http://${app.eureka-server}:8761
      predicates:
        - Path=/eureka/api/{segment}
      filters:
        - SetPath=/eureka/{segment}

    - id: eureka-web-start
      uri: http://${app.eureka-server}:8761
      predicates:
        - Path=/eureka/web
      filters:
        - SetPath=/

    - id: eureka-web-other
      uri: http://${app.eureka-server}:8761
      predicates:
        - Path=/eureka/**

    - id: config-server
      uri: http://${app.config-server}:8888
      predicates:
        - Path=/config/**
      filters:
        - RewritePath=/config/(?<segment>.*), /$\{segment}



management.endpoint.gateway.enabled: true
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---
spring.config.activate.on-profile: docker
app:
  eureka-server: eureka
  auth-server-host: keycloak